import { expect, test } from '@playwright/test';
import { SAMPLE_PLAN } from '../../src/fixtures/sample-plan.js';
import { SAMPLE_SPEC } from '../../src/fixtures/sample-spec.js';
import { mockAnthropic } from './support/anthropic-mock.js';

const GENERATED_PLAN = { ...SAMPLE_PLAN, title: 'Generated plan for the lab' };
const FLAKY_SPEC = {
  ...SAMPLE_SPEC,
  code: SAMPLE_SPEC.code.replace(
    "await page.goto('/');",
    "await page.goto('/');\n    await page.waitForTimeout(500);",
  ),
};

test.describe('Generate with a key (Anthropic API mocked at the network layer)', () => {
  test('brief -> plan -> flaky spec fails lint -> regenerate with feedback -> passes', async ({ page }) => {
    const requests = await mockAnthropic(page, (_request, index) => {
      if (index === 0) return { kind: 'message', text: JSON.stringify(GENERATED_PLAN) };
      if (index === 1) return { kind: 'message', text: JSON.stringify(FLAKY_SPEC) };
      return { kind: 'message', text: JSON.stringify(SAMPLE_SPEC) };
    });

    await page.goto('/');
    await page.getByLabel('Anthropic API key', { exact: true }).fill('sk-ant-test-key');
    await page.getByLabel('Model', { exact: true }).selectOption('claude-opus-5');
    await page.getByRole('radio', { name: /Modern Quality Engineering Lab/ }).check();
    await page.getByRole('checkbox', { name: 'API & contracts' }).check();

    await page.getByRole('button', { name: 'Generate plan' }).click();

    await expect(page.getByRole('heading', { name: GENERATED_PLAN.title })).toBeVisible();
    await expect(page.getByText('generated by Claude')).toBeVisible();

    // Contract of the outbound request: model, cacheable system prompt, brief, structured output.
    expect(requests).toHaveLength(1);
    expect(requests[0].model).toBe('claude-opus-5');
    expect(requests[0].stream).toBe(true);
    expect(requests[0].system).toEqual([expect.objectContaining({ cache_control: { type: 'ephemeral' } })]);
    expect(requests[0].messages[0].content).toContain('Modern Quality Engineering Lab');
    expect(requests[0].messages[0].content).toContain('API & contracts');
    expect(requests[0].output_config?.format?.type).toBe('json_schema');

    await page.getByRole('button', { name: /Generate Playwright spec/ }).click();

    await expect(page.getByTestId('lint-verdict')).toHaveText('failed');
    await expect(page.getByText('no-wait-for-timeout')).toBeVisible();
    await expect(page.getByRole('button', { name: 'Continue to run' })).toBeDisabled();

    await page.getByRole('button', { name: 'Regenerate with lint feedback' }).click();

    await expect(page.getByTestId('lint-verdict')).toHaveText('passed');
    expect(requests).toHaveLength(3);
    expect(requests[2].messages[0].content).toContain('[no-wait-for-timeout]');
    await expect(page.getByRole('button', { name: 'Continue to run' })).toBeEnabled();
  });

  test('a described-only brief with too little text is rejected before any API call', async ({ page }) => {
    const requests = await mockAnthropic(page, () => ({ kind: 'message', text: '{}' }));
    await page.goto('/');
    await page.getByLabel('Anthropic API key', { exact: true }).fill('sk-ant-test-key');
    await page.getByLabel('Description', { exact: true }).fill('too short');

    await page.getByRole('button', { name: 'Generate plan' }).click();

    await expect(page.getByRole('alert')).toContainText('at least 30 characters');
    expect(requests).toHaveLength(0);
  });
});
