import { useState } from 'react';
import type { TestPlan } from '../domain/plan-schema.js';
import type { PlanSource } from '../state.js';
import { planToMarkdown } from '../domain/markdown-export.js';
import { riskScore } from '../domain/plan-schema.js';
import { downloadText } from './download.js';
import { Progress } from './Feedback.js';
import { ScoreSquares } from './ScoreSquares.js';

type Props = {
  plan: TestPlan;
  source: PlanSource;
  selected: string[];
  hasKey: boolean;
  busy: { characters: number } | null;
  onToggle: (id: string) => void;
  onGenerateSpec: () => void;
  onLoadSampleSpec: () => void;
  onCancel: () => void;
};

const isBrowserLayer = (layer: string) => layer === 'e2e' || layer === 'accessibility';

export function PlanView({
  plan,
  source,
  selected,
  hasKey,
  busy,
  onToggle,
  onGenerateSpec,
  onLoadSampleSpec,
  onCancel,
}: Props) {
  const [expanded, setExpanded] = useState<string[]>(() => plan.scenarios.slice(0, 1).map((s) => s.id));
  const toggleExpanded = (id: string) =>
    setExpanded((ids) => (ids.includes(id) ? ids.filter((x) => x !== id) : [...ids, id]));

  const selectable = plan.scenarios.filter((s) => s.automatable && isBrowserLayer(s.layer)).length;
  const slug = plan.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');

  return (
    <>
      <header className="plan-header">
        <div className="stack-12">
          <h2>{plan.title}</h2>
          <p className="summary">{plan.summary}</p>
          <div className="counts">
            <span>{plan.risks.length} risks</span>
            <span aria-hidden="true">·</span>
            <span>{plan.scenarios.length} scenarios</span>
            <span aria-hidden="true">·</span>
            <span>{selectable} selectable for Playwright</span>
          </div>
        </div>
        <div className="aside">
          <span className="stamp">{source === 'sample' ? 'sample plan' : 'generated by Claude'}</span>
          <div className="row-8">
            <button
              type="button"
              className="btn btn-sm"
              onClick={() => downloadText(`${slug}.md`, planToMarkdown(plan), 'text/markdown;charset=utf-8')}
            >
              Download Markdown
            </button>
            <button
              type="button"
              className="btn btn-sm"
              onClick={() => downloadText(`${slug}.json`, JSON.stringify(plan, null, 2), 'application/json')}
            >
              Download JSON
            </button>
          </div>
        </div>
      </header>

      {plan.assumptions.length > 0 && (
        <section className="section tight" aria-labelledby="s-assumptions">
          <div className="section-label" id="s-assumptions">
            Assumptions
          </div>
          <ul className="plain-list mt-8">
            {plan.assumptions.map((a) => (
              <li key={a}>{a}</li>
            ))}
          </ul>
        </section>
      )}

      <section className="section tight" aria-labelledby="s-risks">
        <div className="section-label-row">
          <div className="section-label" id="s-risks">
            2.1 · Risk register
          </div>
        </div>
        <div className="table-wrap">
          <table className="table">
            <thead>
              <tr>
                <th scope="col">Id</th>
                <th scope="col">Area</th>
                <th scope="col">Risk</th>
                <th scope="col" className="num" abbr="Likelihood">
                  L
                </th>
                <th scope="col" className="num" abbr="Impact">
                  I
                </th>
                <th scope="col">Score</th>
                <th scope="col">Mitigation</th>
              </tr>
            </thead>
            <tbody>
              {plan.risks.map((risk) => (
                <tr key={risk.id}>
                  <td className="id">{risk.id}</td>
                  <td className="area">{risk.area}</td>
                  <td className="risk">{risk.description}</td>
                  <td className="num">{risk.likelihood}</td>
                  <td className="num">{risk.impact}</td>
                  <td>
                    <ScoreSquares score={riskScore(risk)} />
                  </td>
                  <td className="mitigation">{risk.mitigation}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="footnote">Score = L × I. Squares ≥ 6 are printed in signal red.</div>
      </section>

      <section className="section tight" aria-labelledby="s-scenarios">
        <div className="section-label-row">
          <div className="section-label" id="s-scenarios">
            2.2 · Scenarios
          </div>
          <span className="note">manual · api · contract · performance rows are not selectable</span>
        </div>
        <div className="rows">
          {plan.scenarios.map((s) => {
            const canSelect = s.automatable && isBrowserLayer(s.layer);
            const open = expanded.includes(s.id);
            return (
              <div key={s.id} className="scenario">
                <div className="line">
                  <input
                    type="checkbox"
                    aria-label={`Select ${s.id} ${s.title}`}
                    checked={selected.includes(s.id)}
                    onChange={() => onToggle(s.id)}
                    disabled={!canSelect}
                  />
                  <span className="id">{s.id}</span>
                  <span className="title">{s.title}</span>
                  <div className="tags">
                    <span className="tag-box">{s.priority}</span>
                    <span className="tag-box quiet">{s.layer}</span>
                    <span className="risks">{s.riskIds.join(' ')}</span>
                  </div>
                  <button
                    type="button"
                    className="toggle"
                    aria-expanded={open}
                    aria-label={`Toggle details for ${s.id}`}
                    onClick={() => toggleExpanded(s.id)}
                  >
                    {open ? '−' : '+'}
                  </button>
                </div>
                {open && (
                  <div className="details">
                    {s.preconditions.length > 0 && (
                      <>
                        <span className="k">Given</span>
                        <span>{s.preconditions.join('; ')}</span>
                      </>
                    )}
                    <span className="k">Steps</span>
                    <ol>
                      {s.steps.map((step) => (
                        <li key={step}>{step}</li>
                      ))}
                    </ol>
                    <span className="k">Expected</span>
                    <ul>
                      {s.expected.map((e) => (
                        <li key={e}>{e}</li>
                      ))}
                    </ul>
                    <span className="k">Oracle</span>
                    <span className="oracle">{s.oracle}</span>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </section>

      {plan.outOfScope.length + plan.openQuestions.length > 0 && (
        <div className="two-col-lists">
          {plan.outOfScope.length > 0 && (
            <section className="section tight" aria-labelledby="s-oos">
              <div className="section-label" id="s-oos">
                Out of scope
              </div>
              <ul className="mt-8">
                {plan.outOfScope.map((o) => (
                  <li key={o}>{o}</li>
                ))}
              </ul>
            </section>
          )}
          {plan.openQuestions.length > 0 && (
            <section className="section tight" aria-labelledby="s-oq">
              <div className="section-label" id="s-oq">
                Open questions
              </div>
              <ul className="mt-8">
                {plan.openQuestions.map((q) => (
                  <li key={q}>{q}</li>
                ))}
              </ul>
            </section>
          )}
        </div>
      )}

      <div className="actions">
        {busy && <Progress label="Writing the Playwright spec" characters={busy.characters} />}
        <div className="row">
          {busy ? (
            <button type="button" className="btn btn-primary" disabled aria-busy="true">
              Generating…
            </button>
          ) : (
            <button
              type="button"
              className="btn btn-primary"
              onClick={onGenerateSpec}
              disabled={!hasKey || selected.length === 0}
            >
              Generate Playwright spec ({selected.length} selected)
            </button>
          )}
          {busy ? (
            <button type="button" className="btn" onClick={onCancel}>
              Cancel
            </button>
          ) : (
            source === 'sample' && (
              <button type="button" className="btn" onClick={onLoadSampleSpec}>
                Load sample spec
              </button>
            )
          )}
          <span className="hint">
            {!hasKey && source !== 'sample'
              ? 'Add an API key in the Brief step to generate code.'
              : 'One spec file, one test per scenario. Manual and API scenarios stay in the Markdown plan.'}
          </span>
        </div>
      </div>
    </>
  );
}
