import type { CSSProperties } from 'react';
import type { TestPlan } from '../domain/plan-schema.js';
import type { PlanSource } from '../state.js';
import { planToMarkdown } from '../domain/markdown-export.js';
import { riskLevel, riskScore } from '../domain/plan-schema.js';
import { downloadText } from './download.js';

type Props = {
  plan: TestPlan;
  source: PlanSource;
  selected: string[];
  hasKey: boolean;
  busy: boolean;
  onToggle: (id: string) => void;
  onGenerateSpec: () => void;
  onLoadSampleSpec: () => void;
};

export function PlanView({
  plan,
  source,
  selected,
  hasKey,
  busy,
  onToggle,
  onGenerateSpec,
  onLoadSampleSpec,
}: Props) {
  const slug = plan.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');

  return (
    <div className="stack">
      <section className="card reveal" aria-labelledby="plan-heading">
        <div className="card-head">
          <div>
            <h2 id="plan-heading">{plan.title}</h2>
            <span className={source === 'sample' ? 'badge badge-amber' : 'badge badge-teal'}>
              {source === 'sample' ? 'sample plan' : 'generated by Claude'}
            </span>
          </div>
          <div className="row">
            <button
              type="button"
              className="btn btn-sm"
              onClick={() => downloadText(`${slug}.md`, planToMarkdown(plan), 'text/markdown;charset=utf-8')}
            >
              Download Markdown
            </button>
            <button
              type="button"
              className="btn btn-sm"
              onClick={() => downloadText(`${slug}.json`, JSON.stringify(plan, null, 2), 'application/json')}
            >
              Download JSON
            </button>
          </div>
        </div>
        <p>{plan.summary}</p>
        {plan.assumptions.length > 0 && (
          <>
            <h3 style={{ marginTop: 18 }}>Assumptions</h3>
            <ul className="muted" style={{ margin: '6px 0 0', paddingLeft: 20 }}>
              {plan.assumptions.map((a) => (
                <li key={a}>{a}</li>
              ))}
            </ul>
          </>
        )}
      </section>

      <section className="card reveal" style={{ '--i': 1 } as CSSProperties} aria-labelledby="risks-heading">
        <div className="card-head">
          <h2 id="risks-heading">Risk register</h2>
          <span className="muted" style={{ fontSize: '0.85rem' }}>
            score = likelihood × impact
          </span>
        </div>
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th scope="col">Id</th>
                <th scope="col">Area</th>
                <th scope="col">Risk</th>
                <th scope="col">L</th>
                <th scope="col">I</th>
                <th scope="col">Score</th>
                <th scope="col">Mitigation</th>
              </tr>
            </thead>
            <tbody>
              {plan.risks.map((risk) => {
                const score = riskScore(risk);
                return (
                  <tr key={risk.id}>
                    <td className="mono">{risk.id}</td>
                    <td>
                      <span className="badge">{risk.area}</span>
                    </td>
                    <td>{risk.description}</td>
                    <td className="mono">{risk.likelihood}</td>
                    <td className="mono">{risk.impact}</td>
                    <td>
                      <span className={`heat heat-${riskLevel(score)}`}>{score}</span>
                    </td>
                    <td className="muted">{risk.mitigation}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </section>

      <section
        className="card reveal"
        style={{ '--i': 2 } as CSSProperties}
        aria-labelledby="scenarios-heading"
      >
        <div className="card-head">
          <h2 id="scenarios-heading">Scenarios</h2>
          <span className="muted" style={{ fontSize: '0.85rem' }}>
            Tick the browser scenarios to turn into a Playwright spec.
          </span>
        </div>
        <div>
          {plan.scenarios.map((s) => {
            const browserLayer = s.layer === 'e2e' || s.layer === 'accessibility';
            const checkboxId = `scenario-${s.id}`;
            return (
              <div key={s.id} className="scenario">
                <input
                  id={checkboxId}
                  type="checkbox"
                  checked={selected.includes(s.id)}
                  onChange={() => onToggle(s.id)}
                  disabled={!s.automatable || !browserLayer}
                  aria-describedby={`${checkboxId}-meta`}
                />
                <div>
                  <label htmlFor={checkboxId} style={{ fontWeight: 600 }}>
                    <span className="mono muted">{s.id}</span> {s.title}
                  </label>
                  <div className="meta" id={`${checkboxId}-meta`}>
                    <span className={s.priority === 'P0' ? 'badge badge-red' : 'badge'}>{s.priority}</span>
                    <span className="badge badge-amber">{s.layer}</span>
                    {s.riskIds.map((r) => (
                      <span key={r} className="badge">
                        {r}
                      </span>
                    ))}
                    {!s.automatable && <span className="badge">manual</span>}
                  </div>
                  <details>
                    <summary>Steps, expected results and oracle</summary>
                    {s.preconditions.length > 0 && (
                      <p className="muted" style={{ fontSize: '0.9rem', marginTop: 6 }}>
                        Preconditions: {s.preconditions.join('; ')}
                      </p>
                    )}
                    <ol>
                      {s.steps.map((step) => (
                        <li key={step}>{step}</li>
                      ))}
                    </ol>
                    <ul>
                      {s.expected.map((e) => (
                        <li key={e}>{e}</li>
                      ))}
                    </ul>
                    <p className="muted" style={{ fontSize: '0.9rem', marginTop: 6 }}>
                      Oracle: {s.oracle}
                    </p>
                  </details>
                </div>
              </div>
            );
          })}
        </div>
        <div className="row" style={{ marginTop: 16 }}>
          <button
            type="button"
            className="btn btn-primary"
            onClick={onGenerateSpec}
            disabled={busy || !hasKey || selected.length === 0}
          >
            Generate Playwright spec ({selected.length} selected)
          </button>
          {source === 'sample' && (
            <button type="button" className="btn" onClick={onLoadSampleSpec} disabled={busy}>
              Load sample spec
            </button>
          )}
          {!hasKey && source !== 'sample' && (
            <span className="muted" style={{ fontSize: '0.85rem' }}>
              Add an API key in the Brief step to generate code.
            </span>
          )}
        </div>
        {plan.outOfScope.length + plan.openQuestions.length > 0 && (
          <div className="grid-2" style={{ marginTop: 22 }}>
            {plan.outOfScope.length > 0 && (
              <div>
                <h3>Out of scope</h3>
                <ul className="muted" style={{ margin: '6px 0 0', paddingLeft: 20, fontSize: '0.9rem' }}>
                  {plan.outOfScope.map((o) => (
                    <li key={o}>{o}</li>
                  ))}
                </ul>
              </div>
            )}
            {plan.openQuestions.length > 0 && (
              <div>
                <h3>Open questions</h3>
                <ul className="muted" style={{ margin: '6px 0 0', paddingLeft: 20, fontSize: '0.9rem' }}>
                  {plan.openQuestions.map((q) => (
                    <li key={q}>{q}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}
      </section>
    </div>
  );
}
